language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t aylinsolak/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true aylinsolak/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react"
    env: "Docker-react-env"
    bucket_name: "elasticbeanstalk-us-west-2-306476627547"
    bucket_path: "docker-react"
    on:
        branch: master
